version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.6
    container_name: moodle_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: moodle_pass123
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - moodle_network

  # Moodle Application
  moodle:
    image: moodlehq/moodle-php-apache:8.1
    container_name: moodle_app
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBHOST: mariadb
      MOODLE_DOCKER_DBPORT: 3306
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle_user
      MOODLE_DOCKER_DBPASS: moodle_pass123
      MOODLE_DOCKER_WWWROOT: http://localhost:8080
      MOODLE_DOCKER_DATAROOT: /var/www/moodledata
    volumes:
      - ./moodle:/var/www/html
      - moodle_data:/var/www/moodledata
    ports:
      - "8080:80"
    networks:
      - moodle_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: moodle_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword123
      MYSQL_ROOT_PASSWORD: rootpassword123
    ports:
      - "8081:80"
    networks:
      - moodle_network

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

networks:
  moodle_network:
    driver: bridge